package diary.constants;

import java.net.URL;

public class PainLocationPath 
{
	public static final String CUSTOM_PAIN_LOC_GENERAL_FOLDER = "/pain_location/custom",
								CUSTOM_PAIN_LOC_BACK_FOLDER = PainLocationPath.CUSTOM_PAIN_LOC_GENERAL_FOLDER + "/mblkng",
								CUSTOM_PAIN_LOC_FRONT_FOLDER = PainLocationPath.CUSTOM_PAIN_LOC_GENERAL_FOLDER + "/mdepan",
								CUSTOM_PAIN_LOC_RIGHT_FOLDER = PainLocationPath.CUSTOM_PAIN_LOC_GENERAL_FOLDER + "/mkanan",
								CUSTOM_PAIN_LOC_LEFT_FOLDER = PainLocationPath.CUSTOM_PAIN_LOC_GENERAL_FOLDER + "/mkiri";
	
	//Back
	public static final URL CUSTOM_PAIN_BACK_1 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang1.jpg"),
							CUSTOM_PAIN_BACK_2 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang2.jpg"),
							CUSTOM_PAIN_BACK_3 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang3.jpg"),
							CUSTOM_PAIN_BACK_4 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang4.jpg"),
							CUSTOM_PAIN_BACK_5 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang5.jpg"),
							CUSTOM_PAIN_BACK_6 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang6.jpg"),
							CUSTOM_PAIN_BACK_7 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang7.jpg"),
							CUSTOM_PAIN_BACK_8 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang8.jpg"),
							CUSTOM_PAIN_BACK_9 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang9.jpg"),
							CUSTOM_PAIN_BACK_10 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang10.jpg"),
							CUSTOM_PAIN_BACK_11 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang11.jpg"),
							CUSTOM_PAIN_BACK_12 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang12.jpg"),
							CUSTOM_PAIN_BACK_13 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang13.jpg"),
							CUSTOM_PAIN_BACK_14 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang14.jpg"),
							CUSTOM_PAIN_BACK_15 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang15.jpg"),
							CUSTOM_PAIN_BACK_16 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang16.jpg"),
							CUSTOM_PAIN_BACK_17 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang17.jpg"),
							CUSTOM_PAIN_BACK_18 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang18.jpg"),
							CUSTOM_PAIN_BACK_19 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang19.jpg"),
							CUSTOM_PAIN_BACK_20 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_BACK_FOLDER + "/mukabelakang20.jpg");
	//Front
	public static final URL CUSTOM_PAIN_FRONT_1 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan1.jpg"),
							CUSTOM_PAIN_FRONT_2 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan2.jpg"),
							CUSTOM_PAIN_FRONT_3 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan3.jpg"),
							CUSTOM_PAIN_FRONT_4 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan4.jpg"),
							CUSTOM_PAIN_FRONT_5 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan5.jpg"),
							CUSTOM_PAIN_FRONT_6 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan6.jpg"),
							CUSTOM_PAIN_FRONT_7 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan7.jpg"),
							CUSTOM_PAIN_FRONT_8 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan8.jpg"),
							CUSTOM_PAIN_FRONT_9 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan9.jpg"),
							CUSTOM_PAIN_FRONT_10 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan10.jpg"),
							CUSTOM_PAIN_FRONT_11 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan11.jpg"),
							CUSTOM_PAIN_FRONT_12 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan12.jpg"),
							CUSTOM_PAIN_FRONT_13 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan13.jpg"),
							CUSTOM_PAIN_FRONT_14 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan14.jpg"),
							CUSTOM_PAIN_FRONT_15 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan15.jpg"),
							CUSTOM_PAIN_FRONT_16 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan16.jpg"),
							CUSTOM_PAIN_FRONT_17 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan17.jpg"),
							CUSTOM_PAIN_FRONT_18 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan18.jpg"),
							CUSTOM_PAIN_FRONT_19 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan19.jpg"),
							CUSTOM_PAIN_FRONT_20 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_FRONT_FOLDER + "/mukadepan20.jpg");
	//Right
	public static final URL CUSTOM_PAIN_RIGHT_1 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan1.jpg"),
							CUSTOM_PAIN_RIGHT_2 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan2.jpg"),
							CUSTOM_PAIN_RIGHT_3 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan3.jpg"),
							CUSTOM_PAIN_RIGHT_4 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan4.jpg"),
							CUSTOM_PAIN_RIGHT_5 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan5.jpg"),
							CUSTOM_PAIN_RIGHT_6 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan6.jpg"),
							CUSTOM_PAIN_RIGHT_7 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan7.jpg"),
							CUSTOM_PAIN_RIGHT_8 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan8.jpg"),
							CUSTOM_PAIN_RIGHT_9 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan9.jpg"),
							CUSTOM_PAIN_RIGHT_10 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan10.jpg"),
							CUSTOM_PAIN_RIGHT_11 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan11.jpg"),
							CUSTOM_PAIN_RIGHT_12 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan12.jpg"),
							CUSTOM_PAIN_RIGHT_13 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan13.jpg"),
							CUSTOM_PAIN_RIGHT_14 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan14.jpg"),
							CUSTOM_PAIN_RIGHT_15 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan15.jpg"),
							CUSTOM_PAIN_RIGHT_16 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan16.jpg"),
							CUSTOM_PAIN_RIGHT_17 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan17.jpg"),
							CUSTOM_PAIN_RIGHT_18 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan18.jpg"),
							CUSTOM_PAIN_RIGHT_19 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan19.jpg"),
							CUSTOM_PAIN_RIGHT_20 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_RIGHT_FOLDER + "/mukakanan20.jpg");
	//Left
	public static final URL CUSTOM_PAIN_LEFT_1 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri1.jpg"),
							CUSTOM_PAIN_LEFT_2 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri2.jpg"),
							CUSTOM_PAIN_LEFT_3 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri3.jpg"),
							CUSTOM_PAIN_LEFT_4 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri4.jpg"),
							CUSTOM_PAIN_LEFT_5 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri5.jpg"),
							CUSTOM_PAIN_LEFT_6 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri6.jpg"),
							CUSTOM_PAIN_LEFT_7 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri7.jpg"),
							CUSTOM_PAIN_LEFT_8 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri8.jpg"),
							CUSTOM_PAIN_LEFT_9 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri9.jpg"),
							CUSTOM_PAIN_LEFT_10 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri10.jpg"),
							CUSTOM_PAIN_LEFT_11 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri11.jpg"),
							CUSTOM_PAIN_LEFT_12 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri12.jpg"),
							CUSTOM_PAIN_LEFT_13 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri13.jpg"),
							CUSTOM_PAIN_LEFT_14 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri14.jpg"),
							CUSTOM_PAIN_LEFT_15 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri15.jpg"),
							CUSTOM_PAIN_LEFT_16 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri16.jpg"),
							CUSTOM_PAIN_LEFT_17 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri17.jpg"),
							CUSTOM_PAIN_LEFT_18 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri18.jpg"),
							CUSTOM_PAIN_LEFT_19 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri19.jpg"),
							CUSTOM_PAIN_LEFT_20 = PainLocationPath.class.getResource(PainLocationPath.CUSTOM_PAIN_LOC_LEFT_FOLDER + "/mukakiri20.jpg");
}
